require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'BareReactNative' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'BareReactNativeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)

    installer.pods_project.targets.each do |target|
      if target.name == "React-Core.common-AccessibilityResources"
        target.remove_from_project
      end
    end
  end
end

target 'BareReactNative-tvOS' do
  # Pods for BareReactNative-tvOS

  target 'BareReactNative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
